### PR TITLE
Opt Out of Graph Traversal

### PR DESCRIPTION
**Pull request by LinqBeast**
Add ability to opt out of graph traversal when you are not working in a disconnected scenario.

### CODE REVIEW

**Comment by lelong37** [comment]
PR accepted and rebased, we'll publish the NuGet packages shortly.

**Comment by tonysneed** [comment]
@lelong37 I figured out what's going on with Travis, which is that this project needs a .travis.yml file at the project root.  I'll add it.

**Comment by tonysneed** [comment]
@lelong37 Did we publish the NuGet packages yet?

**Comment by lelong37** [comment]
Sorry guys been a bit busier than expected, we have not one published as of yet.

**Pull request merged**
